[postgres]
localhost ansible_connection=local ansible_python_interpreter=/home/paulo/.pyenv/shims/python

[postgres:vars]
pg_host=127.0.0.1
pg_port=5432
pg_user=postgres
pg_password=postgres
pg_database=postgres
